name: gale
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - asn1crypto=1.0.1
  - atomicwrites=1.3.0
  - attrs=19.2.0
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2019.8.28
  - cairo=1.14.12
  - cffi=1.12.3
  - chardet=3.0.4
  - cryptography=2.7
  - cudatoolkit=10.1.168
  - cycler=0.10.0
  - cython=0.29.13
  - dbus=1.13.6
  - expat=2.2.6
  - ffmpeg=4.0
  - fontconfig=2.13.0
  - freeglut=3.0.0
  - freetype=2.9.1
  - glib=2.56.2
  - graphite2=1.3.13
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - harfbuzz=1.8.8
  - hdf5=1.10.2
  - idna=2.8
  - importlib_metadata=0.23
  - intel-openmp=2019.4
  - jasper=2.0.14
  - joblib=0.13.2
  - kiwisolver=1.1.0
  - libedit=3.1.20181209
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libglu=9.0.0
  - libopencv=3.4.2
  - libopus=1.3
  - libpng=1.6.37
  - libprotobuf=3.9.2
  - libstdcxx-ng=9.1.0
  - libtiff=4.0.10
  - libuuid=1.0.3
  - libvpx=1.7.0
  - libxcb=1.13
  - libxml2=2.9.9
  - matplotlib=3.1.1
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.14
  - mkl_random=1.1.0
  - more-itertools=7.2.0
  - ncurses=6.1
  - ninja=1.9.0
  - numpy=1.17.2
  - numpy-base=1.17.2
  - olefile=0.46
  - opencv=3.4.2
  - openssl=1.1.1d
  - packaging=19.2
  - pandas=0.25.1
  - patsy=0.5.1
  - pcre=8.43
  - pillow=6.2.0
  - pip=19.2.3
  - pixman=0.38.0
  - pluggy=0.13.0
  - protobuf=3.9.2
  - py=1.8.0
  - py-opencv=3.4.2
  - pycparser=2.19
  - pyopenssl=19.0.0
  - pyparsing=2.4.2
  - pyqt=5.9.2
  - pysocks=1.7.1
  - pytest=5.2.1
  - python=3.7.4
  - python-dateutil=2.8.0
  - pytz=2019.3
  - qt=5.9.7
  - readline=7.0
  - requests=2.22.0
  - scikit-learn=0.21.3
  - scipy=1.3.1
  - seaborn=0.9.0
  - setuptools=41.4.0
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.30.0
  - statsmodels=0.10.1
  - tk=8.6.8
  - tornado=6.0.3
  - tqdm=4.36.1
  - urllib3=1.24.2
  - wcwidth=0.1.7
  - wheel=0.33.6
  - xz=5.2.4
  - zipp=0.6.0
  - zlib=1.2.11
  - zstd=1.3.7
  - certifi=2019.9.11
  - colorlog=4.0.2
  - psutil=5.6.7
  - pycocotools=2.0.0
  - sigopt=5.0.0
  - tensorboardx=1.9
  - icu=58.2
  - jpeg=9b
  - libffi=3.2.1
  - pytorch=1.3.0
  - torchvision=0.4.1
  - pip:
    - argcomplete==1.11.1
    - click==7.0
    - configparser==4.0.2
    - darwin-py==0.3.1
    - docker-pycreds==0.4.0
    - docutils==0.16
    - factory-boy==2.12.0
    - faker==4.0.1
    - gitdb2==2.0.6
    - gitpython==3.0.5
    - gql==0.2.0
    - graphql-core==1.1
    - humanize==1.0.0
    - nvidia-ml-py3==7.352.0
    - pathtools==0.1.2
    - promise==2.3
    - python-polylabel==0.6
    - pyyaml==5.3
    - sentry-sdk==0.14.1
    - sh==1.12.14
    - shortuuid==0.5.0
    - smmap2==2.0.5
    - spectral==0.988
    - subprocess32==3.5.4
    - text-unidecode==1.3
    - torch==1.3.0
    - wandb==0.8.27
    - watchdog==0.10.1

